//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Alumnos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Alumno
    {
        public int Id { get; set; }
        [Required]
        [Display (Name = "Nombre")]
        public string Nombres { get; set; }
        [Required]
        public string Apellido { get; set; }
        [Required]
        public int Edad { get; set; }
        [Required]
        public string Sexo { get; set; }
        [Required]
        public System.DateTime FechaRegistro { get; set; }
        [Required]
        [Display (Name = "Ciudad")]
        public int IdCiudad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
    }
}
